import { z } from "zod";

const envSchema = z.object({
  EXPO_PUBLIC_SUPABASE_URL: z.string().url(),
  EXPO_PUBLIC_SUPABASE_ANON_KEY: z.string().min(20),
  EXPO_PUBLIC_NEWS_API_KEY: z.string().optional(),
  EXPO_PUBLIC_RAPIDAPI_KEY: z.string().optional(),
  EXPO_PUBLIC_GEMINI_API_KEY: z.string().optional(),
  EXPO_PUBLIC_PDFCO_API_KEY: z.string().optional(),
  EXPO_PUBLIC_GROQ_API_KEY: z.string().optional(),
});

const parsed = envSchema.parse({
  EXPO_PUBLIC_SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL,
  EXPO_PUBLIC_SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY,
  EXPO_PUBLIC_NEWS_API_KEY: process.env.EXPO_PUBLIC_NEWS_API_KEY,
  EXPO_PUBLIC_RAPIDAPI_KEY: process.env.EXPO_PUBLIC_RAPIDAPI_KEY,
  EXPO_PUBLIC_GEMINI_API_KEY: process.env.EXPO_PUBLIC_GEMINI_API_KEY,
  EXPO_PUBLIC_PDFCO_API_KEY: process.env.EXPO_PUBLIC_PDFCO_API_KEY,
  EXPO_PUBLIC_GROQ_API_KEY: process.env.EXPO_PUBLIC_GROQ_API_KEY,
});

export const env = {
  ...parsed,
  EXPO_PUBLIC_NEWS_API_KEY: parsed.EXPO_PUBLIC_NEWS_API_KEY ?? "",
  EXPO_PUBLIC_RAPIDAPI_KEY: parsed.EXPO_PUBLIC_RAPIDAPI_KEY ?? "",
  EXPO_PUBLIC_GEMINI_API_KEY: parsed.EXPO_PUBLIC_GEMINI_API_KEY ?? "",
  EXPO_PUBLIC_PDFCO_API_KEY: parsed.EXPO_PUBLIC_PDFCO_API_KEY ?? "",
  EXPO_PUBLIC_GROQ_API_KEY: parsed.EXPO_PUBLIC_GROQ_API_KEY ?? "",
};
