create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  education text not null,
  interests text[] default '{}'::text[] not null,
  projects text[] default '{}'::text[] not null,
  certifications text[] default '{}'::text[] not null,
  resume_text text not null,
  github_url text not null,
  linkedin_url text not null,
  preferred_career_path text not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  name text not null,
  level int default 3 not null check (level between 1 and 5),
  created_at timestamp with time zone default now() not null
);

create table if not exists public.market_trends (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  role text not null,
  demand_score int not null check (demand_score between 0 and 100),
  top_skills text[] default '{}'::text[] not null,
  source text not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.resume_analysis (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  readiness_score int not null check (readiness_score between 0 and 100),
  strengths text[] default '{}'::text[] not null,
  weaknesses text[] default '{}'::text[] not null,
  missing_skills text[] default '{}'::text[] not null,
  ats_feedback text[] default '{}'::text[] not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.career_roadmaps (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  roadmap text[] default '{}'::text[] not null,
  recommendations text[] default '{}'::text[] not null,
  created_at timestamp with time zone default now() not null
);

alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.skills enable row level security;
alter table public.market_trends enable row level security;
alter table public.resume_analysis enable row level security;
alter table public.career_roadmaps enable row level security;

create policy "users_select_own" on public.users for select using (auth.uid() = id);
create policy "users_insert_own" on public.users for insert with check (auth.uid() = id);

create policy "profiles_all_own" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "skills_all_own" on public.skills for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "market_trends_all_own" on public.market_trends for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "resume_analysis_all_own" on public.resume_analysis for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "career_roadmaps_all_own" on public.career_roadmaps for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Optional social links (run for existing databases too)
alter table public.profiles alter column github_url drop not null;
alter table public.profiles alter column linkedin_url drop not null;
